package com.xing.mita.movie.dao.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.xing.mita.movie.entity.ChannelHistory;
import com.xing.mita.movie.entity.Connection;
import com.xing.mita.movie.entity.Download;
import com.xing.mita.movie.entity.HotList;
import com.xing.mita.movie.entity.MovieHistory;
import com.xing.mita.movie.entity.Program;
import com.xing.mita.movie.entity.SearchHistory;
import com.xing.mita.movie.entity.Update;
import com.xing.mita.movie.entity.User;

import com.xing.mita.movie.dao.bean.ChannelHistoryDao;
import com.xing.mita.movie.dao.bean.ConnectionDao;
import com.xing.mita.movie.dao.bean.DownloadDao;
import com.xing.mita.movie.dao.bean.HotListDao;
import com.xing.mita.movie.dao.bean.MovieHistoryDao;
import com.xing.mita.movie.dao.bean.ProgramDao;
import com.xing.mita.movie.dao.bean.SearchHistoryDao;
import com.xing.mita.movie.dao.bean.UpdateDao;
import com.xing.mita.movie.dao.bean.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig channelHistoryDaoConfig;
    private final DaoConfig connectionDaoConfig;
    private final DaoConfig downloadDaoConfig;
    private final DaoConfig hotListDaoConfig;
    private final DaoConfig movieHistoryDaoConfig;
    private final DaoConfig programDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig updateDaoConfig;
    private final DaoConfig userDaoConfig;

    private final ChannelHistoryDao channelHistoryDao;
    private final ConnectionDao connectionDao;
    private final DownloadDao downloadDao;
    private final HotListDao hotListDao;
    private final MovieHistoryDao movieHistoryDao;
    private final ProgramDao programDao;
    private final SearchHistoryDao searchHistoryDao;
    private final UpdateDao updateDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        channelHistoryDaoConfig = daoConfigMap.get(ChannelHistoryDao.class).clone();
        channelHistoryDaoConfig.initIdentityScope(type);

        connectionDaoConfig = daoConfigMap.get(ConnectionDao.class).clone();
        connectionDaoConfig.initIdentityScope(type);

        downloadDaoConfig = daoConfigMap.get(DownloadDao.class).clone();
        downloadDaoConfig.initIdentityScope(type);

        hotListDaoConfig = daoConfigMap.get(HotListDao.class).clone();
        hotListDaoConfig.initIdentityScope(type);

        movieHistoryDaoConfig = daoConfigMap.get(MovieHistoryDao.class).clone();
        movieHistoryDaoConfig.initIdentityScope(type);

        programDaoConfig = daoConfigMap.get(ProgramDao.class).clone();
        programDaoConfig.initIdentityScope(type);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        updateDaoConfig = daoConfigMap.get(UpdateDao.class).clone();
        updateDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        channelHistoryDao = new ChannelHistoryDao(channelHistoryDaoConfig, this);
        connectionDao = new ConnectionDao(connectionDaoConfig, this);
        downloadDao = new DownloadDao(downloadDaoConfig, this);
        hotListDao = new HotListDao(hotListDaoConfig, this);
        movieHistoryDao = new MovieHistoryDao(movieHistoryDaoConfig, this);
        programDao = new ProgramDao(programDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        updateDao = new UpdateDao(updateDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(ChannelHistory.class, channelHistoryDao);
        registerDao(Connection.class, connectionDao);
        registerDao(Download.class, downloadDao);
        registerDao(HotList.class, hotListDao);
        registerDao(MovieHistory.class, movieHistoryDao);
        registerDao(Program.class, programDao);
        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(Update.class, updateDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        channelHistoryDaoConfig.clearIdentityScope();
        connectionDaoConfig.clearIdentityScope();
        downloadDaoConfig.clearIdentityScope();
        hotListDaoConfig.clearIdentityScope();
        movieHistoryDaoConfig.clearIdentityScope();
        programDaoConfig.clearIdentityScope();
        searchHistoryDaoConfig.clearIdentityScope();
        updateDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public ChannelHistoryDao getChannelHistoryDao() {
        return channelHistoryDao;
    }

    public ConnectionDao getConnectionDao() {
        return connectionDao;
    }

    public DownloadDao getDownloadDao() {
        return downloadDao;
    }

    public HotListDao getHotListDao() {
        return hotListDao;
    }

    public MovieHistoryDao getMovieHistoryDao() {
        return movieHistoryDao;
    }

    public ProgramDao getProgramDao() {
        return programDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public UpdateDao getUpdateDao() {
        return updateDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
